### ISSUE TITLE
arrays unsupported

### ISSUE THREAD

**Issue by raineorshine** [zaach/orderly.js#2]
The following simple array schema throws a parse error though it is valid orderly:

``` js
array [
    string;
];
```

Tested at:
http://zaach.github.com/orderly.js/

It should compile into the following json-schema:

``` js
{
  "type": "array",
  "items": {
    "type": "string"
  },
  "additionalProperties": false
}
```

I would love to fix this and submit a pull request but I'm not really sure where to start. I'm using the minified orderly.js for the web and I'm not sure how to test this from source.

**Comment by zaach** [comment]
Thanks, I've updated the grammar to handle this.

**Comment by raineorshine** [comment]
Awesome, thanks!
