### ISSUE TITLE
orderly installation error

### ISSUE THREAD

**Issue by ramkilangodi** [zaach/orderly.js#4]
I am getting the following error while running 'npm install orderly -g'

ERR! Error: No compatible version found: orderly
ERR! No valid targets found.
ERR! Perhaps not compatible with your version of node?
ERR!     at installTargetsError (D:\Ram-installed\nodejs\node_modules\npm\lib\cache.js:424:10)
ERR!     at D:\Ram-installed\nodejs\node_modules\npm\lib\cache.js:406:17
ERR!     at saved (D:\Ram-installed\nodejs\node_modules\npm\lib\utils\npm-registry-client\get.js:136:7)
ERR!     at Object.cb [as oncomplete](D:Ram-installednodejsnode_modulesnpmnode_modulesgraceful-fsgraceful-fs.js:36:9)
ERR! Report this _entire_ log at:
ERR!     http://github.com/isaacs/npm/issues
ERR! or email it to:
ERR!     npm-@googlegroups.com
ERR! 
ERR! System Windows_NT 6.1.7601
ERR! command "D:\Ram-installed\nodejs\\node.exe" "D:\Ram-installed\nodejs\node_modules\npm\bin\npm-cli.js" "install" "orderly"
ERR! cwd D:\Ram-installed\nodejs
ERR! node -v v0.6.2
ERR! npm -v 1.0.106
verbose exit [ 1, true ]

Could you please let me know how to get orderly installed?

**Comment by c4milo** [comment]
hey @zaach, any plans to support nodejs 0.6.x?

**Comment by zaach** [comment]
Gosh, I forgot to publish the update. The newest version with node 0.6.x support should be on npm now.

**Comment by c4milo** [comment]
sweet, thank you @zaach
